2022-03-27 20:35:51,079 INFO aiogram Bot: CodeWarrior [@codewarrior_bot]
2022-03-27 20:35:52,345 WARNING aiogram Updates were skipped successfully.
2022-03-27 20:35:52,345 INFO aiogram.dispatcher.dispatcher Start polling.
2022-03-27 20:36:40,232 ERROR asyncio Task exception was never retrieved
future: <Task finished name='Task-21' coro=<Dispatcher._process_polling_updates() done, defined at c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=OperationalError('no such table: subs')>
Traceback (most recent call last):
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\kurak\Documents\PYTHON\Telegram Bot\bot.py", line 52, in blog_subscriptions
    if db.get_subs(USER_ID)['blog']:
  File "C:\Users\kurak\Documents\PYTHON\Telegram Bot\database.py", line 55, in get_subs
    cursor.execute(f"SELECT * FROM subs WHERE id = {id};")
sqlite3.OperationalError: no such table: subs
2022-03-27 20:39:54,602 INFO aiogram Bot: CodeWarrior [@codewarrior_bot]
2022-03-27 20:39:56,397 WARNING aiogram Updates were skipped successfully.
2022-03-27 20:39:56,397 INFO aiogram.dispatcher.dispatcher Start polling.
2022-03-27 20:40:04,916 ERROR asyncio Task exception was never retrieved
future: <Task finished name='Task-23' coro=<Dispatcher._process_polling_updates() done, defined at c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=OperationalError('near "DUPLICATE": syntax error')>
Traceback (most recent call last):
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\kurak\Documents\PYTHON\Telegram Bot\bot.py", line 62, in subscribe_blog
    db.change_subscription(USER_ID, blog=True)
  File "C:\Users\kurak\Documents\PYTHON\Telegram Bot\database.py", line 19, in change_subscription
    cursor.execute(f"""INSERT INTO subs(id{blog_text[0]}{contests_text[0]})
sqlite3.OperationalError: near "DUPLICATE": syntax error
2022-03-27 20:42:53,669 INFO aiogram Bot: CodeWarrior [@codewarrior_bot]
2022-03-27 20:42:55,127 WARNING aiogram Updates were skipped successfully.
2022-03-27 20:42:55,127 INFO aiogram.dispatcher.dispatcher Start polling.
2022-03-27 20:43:19,040 INFO aiogram Bot: CodeWarrior [@codewarrior_bot]
2022-03-27 20:43:19,373 WARNING aiogram Updates were skipped successfully.
2022-03-27 20:43:19,373 INFO aiogram.dispatcher.dispatcher Start polling.
2022-03-27 20:43:27,144 ERROR asyncio Task exception was never retrieved
future: <Task finished name='Task-23' coro=<Dispatcher._process_polling_updates() done, defined at c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=OperationalError('near "DUPLICATE": syntax error')>
Traceback (most recent call last):
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\kurak\Documents\PYTHON\Telegram Bot\bot.py", line 62, in subscribe_blog
    db.change_subscription(USER_ID, blog=True)
  File "C:\Users\kurak\Documents\PYTHON\Telegram Bot\database.py", line 19, in change_subscription
    cursor.execute(f"""INSERT INTO subs(id{blog_text[0]}{contests_text[0]}) VALUES ({id}{blog_text[1]}{contests_text[1]}) ON DUPLICATE KEY UPDATE {blog_text[2]}{contests_text[2]};""")
sqlite3.OperationalError: near "DUPLICATE": syntax error
2022-03-27 20:46:47,330 INFO aiogram Bot: CodeWarrior [@codewarrior_bot]
2022-03-27 20:46:49,661 WARNING aiogram Updates were skipped successfully.
2022-03-27 20:46:49,661 INFO aiogram.dispatcher.dispatcher Start polling.
2022-03-27 20:46:57,274 ERROR asyncio Task exception was never retrieved
future: <Task finished name='Task-23' coro=<Dispatcher._process_polling_updates() done, defined at c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=OperationalError('near "blog": syntax error')>
Traceback (most recent call last):
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\kurak\Documents\PYTHON\Telegram Bot\bot.py", line 62, in subscribe_blog
    db.change_subscription(USER_ID, blog=True)
  File "C:\Users\kurak\Documents\PYTHON\Telegram Bot\database.py", line 19, in change_subscription
    cursor.execute(f"""INSERT INTO subs(id{blog_text[0]}{contests_text[0]})
sqlite3.OperationalError: near "blog": syntax error
2022-03-27 20:49:00,531 INFO aiogram Bot: CodeWarrior [@codewarrior_bot]
2022-03-27 20:49:00,843 WARNING aiogram Updates were skipped successfully.
2022-03-27 20:49:00,859 INFO aiogram.dispatcher.dispatcher Start polling.
2022-03-27 20:49:01,187 ERROR asyncio Task exception was never retrieved
future: <Task finished name='Task-10' coro=<Dispatcher._process_polling_updates() done, defined at c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=OperationalError('near "blog": syntax error')>
Traceback (most recent call last):
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\kurak\Documents\PYTHON\Telegram Bot\bot.py", line 62, in subscribe_blog
    db.change_subscription(USER_ID, blog=True)
  File "C:\Users\kurak\Documents\PYTHON\Telegram Bot\database.py", line 22, in change_subscription
    cursor.execute(query)
sqlite3.OperationalError: near "blog": syntax error
2022-03-27 20:51:08,418 INFO aiogram Bot: CodeWarrior [@codewarrior_bot]
2022-03-27 20:51:10,720 WARNING aiogram Updates were skipped successfully.
2022-03-27 20:51:10,736 INFO aiogram.dispatcher.dispatcher Start polling.
2022-03-27 20:51:59,902 INFO aiogram Bot: CodeWarrior [@codewarrior_bot]
2022-03-27 20:52:00,873 WARNING aiogram Updates were skipped successfully.
2022-03-27 20:52:00,873 INFO aiogram.dispatcher.dispatcher Start polling.
2022-03-27 20:52:38,564 INFO aiogram Bot: CodeWarrior [@codewarrior_bot]
2022-03-27 20:52:42,535 WARNING aiogram Updates were skipped successfully.
2022-03-27 20:52:42,535 INFO aiogram.dispatcher.dispatcher Start polling.
2022-03-27 20:52:49,012 ERROR asyncio Task exception was never retrieved
future: <Task finished name='Task-23' coro=<Dispatcher._process_polling_updates() done, defined at c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=OperationalError('near "blog": syntax error')>
Traceback (most recent call last):
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\kurak\Documents\PYTHON\Telegram Bot\bot.py", line 63, in subscribe_blog
    db.change_subscription(USER_ID, blog=True)
  File "C:\Users\kurak\Documents\PYTHON\Telegram Bot\database.py", line 20, in change_subscription
    cursor.execute(query)
sqlite3.OperationalError: near "blog": syntax error
2022-03-27 20:55:07,431 INFO aiogram Bot: CodeWarrior [@codewarrior_bot]
2022-03-27 20:55:07,820 WARNING aiogram Updates were skipped successfully.
2022-03-27 20:55:07,823 INFO aiogram.dispatcher.dispatcher Start polling.
2022-03-27 20:55:15,148 ERROR asyncio Task exception was never retrieved
future: <Task finished name='Task-23' coro=<Dispatcher._process_polling_updates() done, defined at c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=OperationalError('near "blog": syntax error')>
Traceback (most recent call last):
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\kurak\Documents\PYTHON\Telegram Bot\bot.py", line 63, in subscribe_blog
    db.change_subscription(USER_ID, blog=True)
  File "C:\Users\kurak\Documents\PYTHON\Telegram Bot\database.py", line 20, in change_subscription
    cursor.execute(query)
sqlite3.OperationalError: near "blog": syntax error
2022-03-27 20:57:52,781 INFO aiogram Bot: CodeWarrior [@codewarrior_bot]
2022-03-27 20:57:53,109 WARNING aiogram Updates were skipped successfully.
2022-03-27 20:57:53,109 INFO aiogram.dispatcher.dispatcher Start polling.
2022-03-27 20:59:51,955 INFO aiogram Bot: CodeWarrior [@codewarrior_bot]
2022-03-27 20:59:52,362 WARNING aiogram Updates were skipped successfully.
2022-03-27 20:59:52,362 INFO aiogram.dispatcher.dispatcher Start polling.
2022-03-27 20:59:56,755 ERROR asyncio Task exception was never retrieved
future: <Task finished name='Task-19' coro=<Dispatcher._process_polling_updates() done, defined at c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=TypeError("'int' object is not subscriptable")>
Traceback (most recent call last):
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "c:\Programs\Python 3.9\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\kurak\Documents\PYTHON\Telegram Bot\bot.py", line 53, in blog_subscriptions
    if db.get_subs(USER_ID)['blog']:
  File "C:\Users\kurak\Documents\PYTHON\Telegram Bot\database.py", line 62, in get_subs
    ans = ans[0][1:]
TypeError: 'int' object is not subscriptable
2022-03-27 21:00:46,840 INFO aiogram Bot: CodeWarrior [@codewarrior_bot]
2022-03-27 21:00:47,168 WARNING aiogram Updates were skipped successfully.
2022-03-27 21:00:47,168 INFO aiogram.dispatcher.dispatcher Start polling.
2022-03-27 21:01:17,653 INFO aiogram Bot: CodeWarrior [@codewarrior_bot]
2022-03-27 21:01:18,630 WARNING aiogram Updates were skipped successfully.
2022-03-27 21:01:18,630 INFO aiogram.dispatcher.dispatcher Start polling.
2022-03-27 21:01:56,555 INFO aiogram Bot: CodeWarrior [@codewarrior_bot]
2022-03-27 21:01:56,877 WARNING aiogram Updates were skipped successfully.
2022-03-27 21:01:56,877 INFO aiogram.dispatcher.dispatcher Start polling.
2022-03-27 21:06:47,103 INFO aiogram Bot: CodeWarrior [@codewarrior_bot]
2022-03-27 21:06:48,472 WARNING aiogram Updates were skipped successfully.
2022-03-27 21:06:48,488 INFO aiogram.dispatcher.dispatcher Start polling.
2022-03-27 21:07:43,749 INFO aiogram Bot: CodeWarrior [@codewarrior_bot]
2022-03-27 21:07:44,488 WARNING aiogram Updates were skipped successfully.
2022-03-27 21:07:44,488 INFO aiogram.dispatcher.dispatcher Start polling.
2022-03-27 21:08:23,778 INFO aiogram Bot: CodeWarrior [@codewarrior_bot]
2022-03-27 21:08:24,090 WARNING aiogram Updates were skipped successfully.
2022-03-27 21:08:24,090 INFO aiogram.dispatcher.dispatcher Start polling.
2022-03-27 21:09:03,482 INFO aiogram Bot: CodeWarrior [@codewarrior_bot]
2022-03-27 21:09:04,892 WARNING aiogram Updates were skipped successfully.
2022-03-27 21:09:04,892 INFO aiogram.dispatcher.dispatcher Start polling.
2022-03-27 21:09:36,754 INFO aiogram Bot: CodeWarrior [@codewarrior_bot]
2022-03-27 21:09:37,480 WARNING aiogram Updates were skipped successfully.
2022-03-27 21:09:37,480 INFO aiogram.dispatcher.dispatcher Start polling.
2022-03-27 21:14:37,583 INFO schedule Running job Every 5 minutes do check_for_new_posts() (last run: [never], next run: 2022-03-27 21:14:37)
2022-03-27 21:14:38,561 WARNING root API is not working now. Skipping...
2022-03-27 21:14:38,562 INFO schedule Running job Every 5 minutes do check_for_nearest_contests() (last run: [never], next run: 2022-03-27 21:14:37)
2022-03-27 21:19:39,174 INFO schedule Running job Every 5 minutes do check_for_new_posts() (last run: 2022-03-27 21:14:38, next run: 2022-03-27 21:19:38)
2022-03-27 21:19:41,399 WARNING root API is not working now. Skipping...
2022-03-27 21:19:42,414 INFO schedule Running job Every 5 minutes do check_for_nearest_contests() (last run: 2022-03-27 21:14:41, next run: 2022-03-27 21:19:41)
2022-03-27 21:24:42,419 INFO schedule Running job Every 5 minutes do check_for_new_posts() (last run: 2022-03-27 21:19:41, next run: 2022-03-27 21:24:41)
2022-03-27 21:24:44,525 WARNING root API is not working now. Skipping...
2022-03-27 21:24:47,567 INFO schedule Running job Every 5 minutes do check_for_nearest_contests() (last run: 2022-03-27 21:19:47, next run: 2022-03-27 21:24:47)
2022-03-27 21:29:44,695 INFO schedule Running job Every 5 minutes do check_for_new_posts() (last run: 2022-03-27 21:24:44, next run: 2022-03-27 21:29:44)
2022-03-27 21:29:45,340 WARNING root API is not working now. Skipping...
2022-03-27 21:29:50,390 INFO schedule Running job Every 5 minutes do check_for_nearest_contests() (last run: 2022-03-27 21:24:49, next run: 2022-03-27 21:29:49)
2022-03-27 21:34:46,312 INFO schedule Running job Every 5 minutes do check_for_new_posts() (last run: 2022-03-27 21:29:45, next run: 2022-03-27 21:34:45)
2022-03-27 21:34:48,324 WARNING root API is not working now. Skipping...
2022-03-27 21:34:57,423 INFO schedule Running job Every 5 minutes do check_for_nearest_contests() (last run: 2022-03-27 21:29:56, next run: 2022-03-27 21:34:56)
